manifest:
  remotes:
    - name: maxschipper
      url-base: https://github.com/maxschipper
  projects:
    - name: zmk
      remote: maxschipper
      revision: ae8299ed
      import: app/west.yml
  self:
    path: config
